version: 2

jobs:
  build:
    environment:
      SBT_VERSION: 1.11.4
      SBT_OPTS: "-Xms512M -Xmx1536M -Xss1M"
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache
      - run: sbt clean test:compile scripted
      - save_cache:
          key: dependency-cache
          paths:
            - ~/.sbt

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
