name: gh-actions
run-name: ${{ github.actor }} triggered a Github Action
on: [push]
jobs:
  sanity-checks:
    env:
      MC_TOKEN_USER: ${{ secrets.MAVEN_CENTRAL_TOKEN_USER }}
      MC_TOKEN_PASS: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
      SBT_VERSION: 1.11.4
      SBT_OPTS: "-Xms512M -Xmx1536M -Xss1M"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Our environment
        run: env | sort
      - name: Organisation secrets
        run: |
          echo "MAVEN_CENTRAL_TOKEN_USER starts with ${MC_TOKEN_USER:0:1} and is ${#MC_TOKEN_USER} long"
          echo "MAVEN_CENTRAL_TOKEN_PASSWORD starts with ${MC_TOKEN_PASS:0:1} and is ${#MC_TOKEN_PASS} long"
      - name: Perform the tests
        run: sbt clean test:compile scripted
